SET PAGESIZE 50;
SET LINESIZE 200;
SELECT SHOWID, SHOWDATE, "SHOW" FROM "SHOW" WHERE ROWNUM <= 10 ORDER BY SHOWDATE DESC;
SELECT USERID FROM USERS WHERE ROWNUM <= 1;
SELECT SEATID FROM SEAT WHERE ROWNUM <= 1;
EXIT;
