//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kumariCinema_Sharvik
{


    public partial class DashboardPage
    {

        /// <summary>
        /// lblTotalUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTotalUsers;

        /// <summary>
        /// lblTotalMovies control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTotalMovies;

        /// <summary>
        /// lblTotalHalls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTotalHalls;

        /// <summary>
        /// lblTicketsSold control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTicketsSold;

        /// <summary>
        /// rptTopHalls control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptTopHalls;

        /// <summary>
        /// phNoDataHalls control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phNoDataHalls;
    }
}
