SET PAGESIZE 50;
SET LINESIZE 200;
-- Find a seat not occupied for show 1
SELECT SEATID FROM SEAT WHERE ROWNUM = 1 AND SEATID NOT IN (
    SELECT t.SEATID FROM TICKET t JOIN BOOKING_TICKET bt ON t.TICKETID = bt.TICKETID JOIN BOOKING b ON bt.BOOKINGID = b.BOOKINGID WHERE b.SHOWID = 1
);
EXIT;
