SET FEEDBACK ON;
BEGIN
  -- Cleanup just in case
  DELETE FROM BOOKING_TICKET WHERE TICKETID = 9999;
  DELETE FROM TICKET WHERE TICKETID = 9999;
  DELETE FROM BOOKING WHERE BOOKINGID = 9999;
  
  -- Insert into BOOKING (March 17th show)
  INSERT INTO BOOKING (BOOKINGID, BOOKINGDATE, SHOWID, BOOKINGSTATUS)
  VALUES (9999, DATE '2026-03-17', 1, 'Pending');
  
  -- Insert into TICKET
  INSERT INTO TICKET (TICKETID, TICKETPRICE, TICKETSTATUS, SEATID)
  VALUES (9999, 300, 'Pending', 579);
  
  -- Map to BOOKING_TICKET
  INSERT INTO BOOKING_TICKET (BOOKINGID, TICKETID, USERID)
  VALUES (9999, 9999, 1);
  
  COMMIT;
END;
/
EXIT;
