//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kumariCinema_Sharvik
{
    public partial class MovieDetails
    {
        protected global::System.Web.UI.WebControls.GridView GridViewMovies;
        protected global::System.Web.UI.WebControls.DetailsView DetailsViewMovie;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceMovies;
    }
}
