SET PAGESIZE 50;
SET LINESIZE 200;
-- Get a user
SELECT USERID FROM USERS WHERE ROWNUM = 1;
-- Get a show for the future (Mar 19)
SELECT SHOWID, SHOWDATE FROM "SHOW" WHERE SHOWDATE = DATE '2026-03-19' AND ROWNUM = 1;
-- Get a seat
SELECT SEATID FROM SEAT WHERE ROWNUM = 1;
EXIT;
