//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kumariCinema_Sharvik
{
    public partial class TheaterCityHallDetails
    {
        protected global::System.Web.UI.WebControls.GridView GridViewTheaters;
        protected global::System.Web.UI.WebControls.DetailsView DetailsViewTheater;
        protected global::System.Web.UI.WebControls.Label lblTheaterMessage;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceTheaters;

        protected global::System.Web.UI.WebControls.GridView GridViewHalls;
        protected global::System.Web.UI.WebControls.DetailsView DetailsViewHall;
        protected global::System.Web.UI.WebControls.Label lblHallMessage;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceHalls;
        
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceTheaterDropdown;
    }
}
